name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu]
        config: [debug, release]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        shell: bash
        run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd .. && sudo apt-get install python2.7 cmake default-jre && npm ci

      - name: build
        shell: bash
        run: npm run build:${{ matrix.config }}

      - name: test
        shell: bash
        run: npm test
